export enum TextStatisticEvent {
    ON_SEND_CALCULATE_RESULT = '_ON_SEND_CALCULATE_RESULT',
    ON_SEND_DATA_FROM_STAT = '_ON_SEND_DATA_FROM_STAT',
    ON_SEARCH_WORD_IN_DB = '_ON_SEARCH_WORD_IN_DB'
}